name: RNA_seq_read_quant_env

channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - black=23.3.0
  - ruff=0.4.10
  - snakefmt=0.8.5
  - snakemake=7.24
  - r-styler=1.7.0
  - pandas=1.4.2
  - pip
  - pytest=8.2.2

  - pip:
    - -e .
